trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: 'Chandan' # Managed node pool name

stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub-connection'
        repository: 'cloudops96/chandan-cloudops'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'boardgame'
        addPipelineData: false
        addBaseImageData: false
        
    - task: SonarQubePrepare@6
      inputs:
        SonarQube: 'sonar'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'Boardgame'
        cliProjectName: 'Boardgame'
        cliSources: '.'
        extraProperties: |
          # Additional properties that will be passed to the scanner, 
          # Put one key=value per line, example:
          # sonar.exclusions=.
          sonar.java.binaries= .

    - task: SonarQubeAnalyze@6
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'

    
    
    - task: CmdLine@2
      inputs:
        script: 'trivy fs --format table -o trivy-fs-report.html .'
    - task: CmdLine@2
      inputs:
        script: 'trivy image --format table -o trivy-images-report.html cloudops96/chandan-cloudops:boardgame'


