trigger:
  branches:
    include:
      - main
      

pr:
  branches:
    include:
      - main
     

# resources:
# - repo: self
#   type: git
#   connection: 'GitHubConnection' # Ensure this is set up in Azure DevOps to connect with your GitHub repo


# Secrets stored in Azure DevOps Library (Variable Group or Pipeline-level variables)
# dockerRegistryServiceConnection, SONARQUBE_ENDPOINT, TRIVY_API_KEY

pool:
  name: 'Chandan' # Replace this with the name of your managed node pool

stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub-connection'
        repository: 'cloudops96/chandan-cloudops'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'boardgame'
        addPipelineData: false
        addBaseImageData: false
    - task: SonarQubePrepare@6
      inputs:
        SonarQube: 'sonar'
        scannerMode: 'CLI'
        configMode: 'file'

