trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: 'Chandan' # Managed node pool name

stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub-connection'
        repository: 'cloudops96/chandan-cloudops'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'boardgame'
        addPipelineData: false
        addBaseImageData: false
        
    - task: SonarQubePrepare@6
      inputs:
        SonarQube: 'sonar'
        scannerMode: 'CLI'
        configMode: 'file'
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    
    
    - task: CmdLine@2
      inputs:
        script: 'trivy fs --format table -o trivy-fs-report.html .'
    - task: CmdLine@2
      inputs:
        script: 'trivy image --format table -o trivy-images-report.html cloudops96/chandan-cloudops:boardgame'


